%***************************************************************/
%*                                                             */
%*     VAR analysis: compute marginal data density             */
%*                                                             */
%***************************************************************/

% vm_spec 

%******************************************************** 
% Import data series to determine length of sample      *
%*******************************************************/
% vm_loaddata
% 
% nobs = size(YY,1)-T0;  
% nv   = size(YY,2);

%******************************************************** 
%* open output generated by vm_dummy.g 
%* dummy  YYdum XXdum 
%* actual YYact XXact 
%*******************************************************/

% YY=[YYdum' YYact']';
% XX=[XXdum' XXact']';
% YYdum=YYdum;
% XXdum=XXdum;
% 


n_total = T*(1+lambda);
n_dummy = T*lambda;
% nv     = size(YY,2);
k      = n*p; 

YY = T*YY;
XX = T*XX;
XY = T*XY;
YYdum = T*YYdum;
XXdum = T*XXdum;
XYdum = T*XYdum;

%******************************************************** 
%* Compute the log marginal data density for the VAR model 
%*******************************************************/

Phi0   = (inv(XXdum))*(XYdum);
S0     = (YYdum)-XYdum'*(inv(XXdum))*XYdum; 

Phi1   = (inv(XX))*(XY); 
S1     = (YY)-XY'*(inv(XX))*XY;

%* compute constants for integrals

i=1;  
gam0=0; 
gam1=0; 

while i <= nv; 
   gam0=gam0+log(gamma(0.5*(n_dummy-k+1-i))); 
   gam1=gam1+log(gamma(0.5*(n_total-k+1-i))); 
   i=i+1; 
end; 

%** dummy observation

lnpY0 = -nv*(n_dummy-k)*0.5*log(pi)-(nv/2)*log(abs(det(XXdum'*XXdum)))...
      -(n_dummy-k)*0.5*log(abs(det(S0)))+nv*(nv-1)*0.25*log(pi)+gam0;

%** dummy and actual observations
   
lnpY1 = -nv*(n_total-k)*0.5*log(pi)-(nv/2)*log(abs(det(XX'*XX)))...
      -(n_total-k)*0.5*log(abs(det(S1)))+nv*(nv-1)*0.25*log(pi)+gam1;  

% Marginal Likelihood  
lnpYY = lnpY1-lnpY0 ;

% save lnpYY 


